### ISSUE TITLE
meeting to discuss future evolutions of ql

### ISSUE THREAD

**Issue by chicco785** [orchestracities/ngsi-timeseries-api#199]
Dear All,
@AngeloIapichino @ohylli @pooja1pathak @heikkilv @juliozinga @agaldemas @versatildefuy @demestav 

will you be interested in discussing together about features and contributing to the evolution of quantum leap?

Cheers,
Federico on behalf of Martel team

**Comment by ohylli** [comment]
Thank you for the invite. Both I and @heikkilv are interested in participating. We both work at [Tampere University](http://www.tuni.fi/en), Unit of Computer Sciences. We use FIWARE in the [CityIoT](https://www.cityiot.fi/english) project.

**Comment by AngeloIapichino** [comment]
Thank you! I work for Intellimech and we are in the FIWARE foundation. I'm surely interested in your proposal :) We use FIWARE in the FASTEN project

**Comment by chicco785** [comment]
@c0c0n3 @taliaga can you set up a doodle and share here the link?

before the meeting, we will create as well a google document to share with you, so you can put topics for the call

**Comment by c0c0n3** [comment]
Done, here's the link to the Doodle:

https://doodle.com/poll/b2ia8k2mbs9baw4n

I don't have your email addresses so I wasn't able to send you an invite but anyone with the link should be able to vote. I was thinking we could try scheduling the call in the first week of June so I set up the Doodle accordingly---time slots in Zürich time (GMT+2). If that week doesn't work for some of you, we can try the following one.

**Comment by demestav** [comment]
Thank you for the invite @chicco785 . What channel of communication is planned for the meeting?

**Comment by chicco785** [comment]
we will provide an hangout, if that's ok to everyone

**Comment by c0c0n3** [comment]
Hello everyone,

Considering the Doodle poll and our schedule for this week, it looks like the best option for the meeting would be

* **Friday the 7th of June from 11am to 12am**

We've set up a Google Hangouts, please join using the link below:

* meet.google.com/dvu-hsfs-mjd

Tentative agenda:

* New features to develop and their priorities
* Enhancements and fixes
* Collaboration options

@AngeloIapichino @ohylli @pooja1pathak @heikkilv @juliozinga @agaldemas @versatildefuy @demestav I don't have your email addresses so I couldn't add you to the meeting room, but you should still be able to join the meeting using the above link. If you email me an address I could use for the invite, I'll gladly add you to the Hangouts meeting---just to be on the safe side! My one is:

    andrea?falconi?martel-innovate?com

replace question marks in this order: `.`, `@`, `.`. 

@chicco785 please get in touch with Cornelio since I don't have any of his contact details. Thanks!

Look forward to meeting you all on Friday!

**Comment by chopmann** [comment]
@c0c0n3 cornelio.hopmann(--)wobcom.de

**Comment by pooja1pathak** [comment]
Hi @c0c0n3, 
Could you please provide the time-zone for meeting. My email Id is: pooja1pathak@gmail.com. 
If possible, kindly add my team member in the meeting and his email-id is kr.chandradeep@gmail.com.

**Comment by c0c0n3** [comment]
Hi @pooja1pathak,

I've added your and your colleague's emails to the invite, you both should get a confirmation email soon.

Meeting will be at 11am Zurich time---Central European Summer Time (GMT +2).

Thanks!

**Comment by chicco785** [comment]
https://docs.google.com/document/d/1Ik5obEgrci7HZkI_I7e7Yimi3GrdYQXwRYYfe2ZKjpQ/edit#

**Comment by agaldemas** [comment]
Hello, sorry was not available for the meeting, but I'm interested to participate further, 
@ Eridanis (FIWARE gold member since 11/2018), we promoted the use of QL/CrateDB/Grafana as an alternative to STH
Our experience:
- while the project @nice metropole smart city team, using QL with high frequency input from Orion, show performance issues, location information, postal address, complex AirQuality data.
- We want to use it in industrial analytics cases (such as predictive maintenance on high speed complex  process, where milliseconds might become mandatory to discriminate events)

then to summarize our interest (and will to participate to QL evolution)

1. data "timestamping" at millisecond resolution (something like choose 1/2 default attributes name for time_index, in a configurable list, with capture of milliseconds in timestamp value is a first idea)
2. multi-threading to improve performances (upgrade flask version first ?, base architecture on NIFI ?)

Hope this post meeting comment will help, I'll try to follow more closely, in any case I'll introduce a new Eridanis colleague to improve reactivity.

**Comment by chicco785** [comment]
hi @agaldemas 

can you clarify:

> while the project @nice metropole smart city team, using QL with high frequency input from Orion, show performance issues, location information, postal address, complex AirQuality data.

are you experiencing perfomance issues sending data to QL?

> data "timestamping" at millisecond resolution (something like choose 1/2 default attributes name for time_index, in a configurable list, with capture of milliseconds in timestamp value is a first idea)

i believe this is already implemented, at least partially. QL as such supports milliseconds. The issue is the notification. PR #176 introduced new strategy to set time index and also provided a way to configure it via notification.

> multi-threading to improve performances (upgrade flask version first ?, base architecture on NIFI ?)

We use QL in a cluster and performs quite well. Still we think that to improve reliabiliy and performance could be good to introduce a [Queue Centric Workflow pattern](https://kostasbariotis.com/queue-centric-workflow/).

**Comment by pooja1pathak** [comment]
Hi @chicco785 @c0c0n3 
As discussed in the meeting regarding Coverage tool, my colleague has raised an issue #215 for the same. We have investigated the integration of coveralls with travis which is working as expected. 
We have also investigated CodeClimate for the same. But as per our analysis coveralls will be better to use.

Please provide your input so that we can raise PR for this.

**Comment by pooja1pathak** [comment]
Hi @chicco785 @c0c0n3 @taliaga 

Our team raised the PR #221 for coverage tool integration.
Please look into this and provide your comments if any.

Thanks

**Comment by agaldemas** [comment]
Hi @chicco785, sorry for late reply, find hereafter my answers
> 
> can you clarify:
> 
> > while the project @nice metropole smart city team, using QL with high frequency input from Orion, show performance issues, location information, postal address, complex AirQuality data.
> 
> are you experiencing perfomance issues sending data to QL?
**AG: using Orion subscription, to feed QL, we experiment some loss of notification messages, we had to configure the queue system in Orion to avoid this issue.**

> > data "timestamping" at millisecond resolution (something like choose 1/2 default attributes name for time_index, in a configurable list, with capture of milliseconds in timestamp value is a first idea)
> 
> i believe this is already implemented, at least partially. QL as such supports milliseconds. The issue is the notification. PR #176 introduced new strategy to set time index and also provided a way to configure it via notification.
**AG: I read about PR #176, if "TimeInstant" attribute is considered, high priority  than "dateModified" and that the milliseconds are captured, it's perfect !**
> 
> > multi-threading to improve performances (upgrade flask version first ?, base architecture on NIFI ?)
**AG: I noticed that the flask version used is 0.12, which is not multithreaded, it seems that multithreading is supported in version 1.0 ([current is 1.1.1](https://github.com/pallets/flask/releases)), but may be I'm wrong, then don't worry**
> 
> We use QL in a cluster and performs quite well. Still we think that to improve reliability and performance could be good to introduce a [Queue Centric Workflow pattern](https://kostasbariotis.com/queue-centric-workflow/). Ideally when notifications arrives, they are stored in a distributed queue. Then each instance pick the first notification in the queue and stores it.
**AG: using queue can improve reliability, but performance, I doubt.**
